title: 'Scott N Andrew'
default_lang: en
author:
  name: 'Scott N Andrew'
  email: art@scottnandrew.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
